### ISSUE TITLE
Anaconda installation

### ISSUE THREAD

**Issue by wpmccormick** [cjdrake/pyeda#143]
What is the proper way to install on Anaconda?

**Comment by cjdrake** [comment]
I've never used Anaconda. Not sure.

**Comment by rameshKrSah** [comment]
@wpmccormick  Did you figure how to install on Anaconda?

**Comment by AlephG** [comment]
For whoever is still looking for a way to do this, in your terminal or cmd line:

`conda skeleton pypi pyeda `
`conda build pyeda`
`conda install --use-local pyeda`

Cheers!

**Comment by cjdrake** [comment]
Looks good to me.
