### ISSUE TITLE
Warning: collections.abc instead of collections deprecated

### ISSUE THREAD

**Issue by kitaniboy** [cjdrake/pyeda#172]
I got the following warning from pytest:

  ...../site-packages/pyeda/boolalg/bfarray.py:1033: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    if not isinstance(objs, collections.Sequence):

can be solved simply by adding
`
import collections.abc as collections
`
and then `collections` can be renamed to `collections_abc` for example and all instances will change accordingly.

**Comment by cjdrake** [comment]
Pretty sure this is fixed now in `main` branch. The question of having a 3.11 release is a separate issue.
