### ISSUE TITLE
Expression to_dot syntax error

### ISSUE THREAD

**Issue by fzanollo** [cjdrake/pyeda#182]
It seems a typo was added in some cleaning of the expr.py file at commit [Lint cleanup: expr.py](https://github.com/cjdrake/pyeda/commit/adc1c60530b542a1ed16e63e361bc4fd3dbfd211), changing ' for ".

Solution: 
change
```
    def to_dot(self, name="EXPR"): # pragma: no cover
        """Convert to DOT language representation."""
        parts = ["graph", name, "{', 'rankdir=BT;"]
```
to 
```
    def to_dot(self, name="EXPR"): # pragma: no cover
        """Convert to DOT language representation."""
        parts = ["graph", name, "{", "rankdir=BT;"]
```

I'm ready to create a pull request if it helps you at all, thank you for this useful library!

**Comment by cjdrake** [comment]
Nice find :). Yes, please create a pull request.
